GET http://localhost:8082/product HTTP/1.1

###
GET http://localhost:8082/product/details/4 HTTP/1.1


###
DELETE http://localhost:8082/product/delete/5 HTTP/1.1

###
POST http://localhost:8082/product/store HTTP/1.1
content-type: application/json

{
    "title": "Earphone",
    "price": 300,
    "description": "This is very good",
    "published" : true
}

###
POST http://localhost:8082/product/update/4 HTTP/1.1
content-type: application/json

{
    "title": "Iphone13 pro max",
    "price": 1000,
    "description": "This is very good",
    "published" : false
}
