@routeName = user-info
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1

###
GET {{host}}user/1/info HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "user_id": 2,
        "first_name": "alif",
        "last_name": "sagir",
        "designation": "student",
        "date_of_birth": "2022-10-12",
        "phone_number": "01778639643"
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "user_id": 1,
        "first_name": "abdullah",
        "last_name": "sadik",
        "designation": "student",
        "date_of_birth": "2022-10-12",
        "phone_number": "01798398934"
}
