@routeName = user-work-department
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
GET {{host}}user/2/department HTTP/1.1




###
DELETE {{host}}{{routeName}}/delete/2 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "work_id": 3,
        "title": "teacher"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
     "work_id": 3,
        "title": "Engineer"
}
