@routeName = user-work-user
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "user_id": 3,
        "work_id": 2,
        "department_id": 2
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
    "user_id": 3,
        "work_id": 2,
        "department_id": 2
}
